import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner/Banner'
import BannerFooter from '../components/BannerFooter/BannerFooter'
import Feature from '../components/Feature/Feature'
import styles from '../styles/Home.module.css'

import { useGetProductsQuery } from '../services/fetchProducts'


export default function Home() {
  const { data} = useGetProductsQuery('bulbasaur')
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Shows-Shop-app</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner />
      <BannerFooter />
      <Feature />
      </main>


    </div>
  )
}
