import React, {useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Banner from '../components/Banner/Banner'
import BannerFooter from '../components/BannerFooter/BannerFooter'
import Feature from '../components/Feature/Feature'
import styles from './Index.module.css'

import { useGetProductsQuery } from '../services/fetchProducts'

import Product from '../components/Product/Product'

// //all products***//

import { getAllProducts } from '../feactures/allProductsSlice'
import { useDispatch, useSelector } from 'react-redux'



export default function Home() {

  const dispatch= useDispatch();
   let products=useSelector((state=>state.products))
   products=products.products

  
  useEffect(() => {
       dispatch(getAllProducts())
    }, [])


  //const { data} = useGetProductsQuery('bulbasaur')
  //console.log(data)


  return (
    <div className={styles.container}>
      <Head>
        <title>Shows-Shop-app</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner />
      <BannerFooter />
      <div className={styles.releventContainer}>
        <div className={styles.header}>
        <h4><Link href="/products"><a>مشاهده همه</a></Link></h4>
          
          <h2>جدیدترین ها</h2>
        </div>
<div className={styles.relevent}>
   {products && products.slice(0,4).map((item)=>{
  return <Product key={item.id}{...item}/>
  })}  
  </div>
      </div>


      <div className={styles.releventContainer}>
        <div className={styles.header}>
        
        <h4><Link href="/products"><a>مشاهده همه</a></Link></h4>
          <h2>پرفروش ترین ها</h2>
        </div>
 <div className={styles.relevent}>
            {products && products.slice(0,4).map((item)=>{
          return <Product key={item.id}{...item}/>
           })}  
  </div>
      </div>


      <Feature />
      </main>


    </div>
  )
}
