import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner/Banner'
import BannerFooter from '../components/BannerFooter/BannerFooter'
import Feature from '../components/Feature/Feature'
import styles from './Index.module.css'

import { useGetProductsQuery } from '../services/fetchProducts'

import Product from '../components/Product/Product'

//all products***//
import{ products }from '../services/productsList'


export default function Home() {
  const { data} = useGetProductsQuery('bulbasaur')
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Shows-Shop-app</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner />
      <BannerFooter />
      <div className={styles.relevent}>
      {products.slice(0, 4).map((item)=>{
      return <Product key={item.id} {...item}/>
    })}
      </div>
      <Feature />
      </main>


    </div>
  )
}
